CONTIKI_PROJECT = test-sht75
all: $(CONTIKI_PROJECT)
TARGET = avr-zigduino
CONTIKI = ../../../..
#UIP_CONF_IPV6 = 1
CFLAGS += -Wno-deprecated-declarations -D__PROG_TYPES_COMPAT__

include $(CONTIKI)/Makefile.include
